# Use this file to create a conda environment with the command: conda env create -f environment.yml
name: pygskit
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.11
  - openjdk=11
  - openblas
  - lapack
  - pip
  - pip:
      - click
      - setuptools
      - gnomad~=0.8.2
      - hail==0.2.120
variables:
  JAVA_HOME: $CONDA_PREFIX
