# Use this file to create a conda environment with the command: conda env create -f environment.yml
name: pygskit
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
      - click~=8.1.7
      - setuptools~=68.2.0
      - gnomad==0.8.2
      - hail==0.2.120
