# Use this file to create a conda environment with the command: conda env create -f environment.yml
name: pygskit
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
      - click
      - gnomad
      - hail==0.2.120
